name: Release Build

on:
  release:
    types: [unpublished]

permissions:
  contents: read

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      - run: chmod +x gradlew
      - run: ./gradlew :packageReleaseDistributionForCurrentOS
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ubuntu Build
          path: build/compose/binaries/main-release/deb/uniconv_2.1_amd64.deb
  macos-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      - run: chmod +x gradlew
      - run: ./gradlew :packageReleaseDistributionForCurrentOS
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS Build
          path: build/compose/binaries/main-release/dmg/*
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      - run: ./gradlew :packageReleaseDistributionForCurrentOS
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows Build
          path: build/compose/binaries/main-release/msi/Uniconv-2.1.0.msi